services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      JWT_SECRET: "change_this_to_a_strong_secret"
      DATABASE_URL: "mysql://root:TroYzBoY%234023@host.docker.internal:3307/docker_test_db"
    depends_on:
      - rabbitmq

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:5000"
    depends_on:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
