version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DATABASE_URL: mysql://root:root@db:3306/school
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6380:6379"

  seed:
    build: ./backend
    environment:
      DATABASE_URL: mysql://root:root@db:3306/school
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "npx prisma db push && npm run seed"]

volumes:
  db-data:
